repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]
# Run the Ruff linter.
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.3
  hooks:
    # Run the Ruff linter.
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]
    # Run the Ruff formatter.
    - id: ruff-format
-   repo: local
    hooks:
      - id: pylint-error-count
        name: pylint-error-count
        entry: bash -c 'open raycast://confetti || true'
        language: system
        types: [python]
        pass_filenames: false
